# -*- coding: utf-8 -*-
"""sentiment-analysis-v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A3zGDsxBYtKKcvxWSCbIfaLwcCXY80zV
"""

# ============================================================
# CELL 1: Install Required Libraries
# ============================================================
# Run this first. Restart runtime after installing if prompted.

!pip install -q \
    transformers accelerate bitsandbytes \
    yfinance xgboost scikit-learn \
    pandas numpy gnews tqdm lightgbm \
    trafilatura deep-translator \
    seaborn matplotlib ipywidgets joblib

print("✅ All libraries installed. Restart runtime if prompted, then run from Cell 2.")

# ============================================================
# CELL 2: Imports & Global Configuration
# ============================================================
import os, gc, json, time, datetime, warnings, urllib.parse, urllib3
import numpy as np
import pandas as pd
import torch
import lightgbm as lgb
import joblib
import seaborn as sns
import matplotlib.pyplot as plt
import ipywidgets as widgets
from IPython.display import display, clear_output, HTML
from transformers import (
    pipeline, AutoModelForCausalLM, AutoTokenizer,
    BitsAndBytesConfig, logging as hf_logging
)
from sklearn.model_selection import TimeSeriesSplit
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score, classification_report
from xgboost import XGBClassifier
from gnews import GNews
from deep_translator import GoogleTranslator
import trafilatura
import requests

warnings.filterwarnings('ignore')
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
hf_logging.set_verbosity_error()

# ── HuggingFace Token ─────────────────────────────────────
try:
    from google.colab import userdata
    hf_token = userdata.get('HF_TOKEN')
    print("✅ HF_TOKEN loaded from Colab secrets.")
except Exception:
    hf_token = None
    print("⚠️  HF_TOKEN not found. Gated models may fail.")

# ── Device ────────────────────────────────────────────────
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"\n🖥️  Device: {device}")
if device == "cuda":
    total_vram = torch.cuda.get_device_properties(0).total_memory / 1024**3
    print(f"   GPU: {torch.cuda.get_device_name(0)}")
    print(f"   VRAM: {total_vram:.1f} GB")

# ── Global Constants ──────────────────────────────────────
VALID_CATEGORIES = [
    "Earnings & Output", "Analyst Ratings", "Market Action",
    "Deals & Acquisitions", "Macro & Policy", "Other"
]
SENTIMENT_FEATURES = [f"Sentiment_{c}" for c in VALID_CATEGORIES]
COUNT_FEATURES     = [f"Count_{c}"     for c in VALID_CATEGORIES]
ALL_FEATURES       = SENTIMENT_FEATURES + COUNT_FEATURES

# Noise threshold: ignore trading days where |return| < 0.3%
# These "flat" days are pure noise and hurt model training.
RETURN_THRESHOLD = 0.003

# Exponential time-decay for news recency (λ = 0.1 → 5-day-old news = 60% weight)
DECAY_LAMBDA = 0.1

# Lookback window: how many days of past news to include per trading day
NEWS_LOOKBACK_DAYS = 5

# Paths
SAVE_DIR    = "/content/saved_models"
CSV_FILENAME = "master_stock_sentiment_db.csv"
os.makedirs(SAVE_DIR, exist_ok=True)

# Will be populated by Cell 4.5 winner
SENTIMENT_MODEL_NAME = None
active_sentiment_pipe = None

print("\n✅ Global configuration complete.")
print(f"   Features: {len(ALL_FEATURES)} ({len(SENTIMENT_FEATURES)} sentiment + {len(COUNT_FEATURES)} count)")
print(f"   Return noise threshold: ±{RETURN_THRESHOLD*100:.1f}%")
print(f"   Time-decay λ: {DECAY_LAMBDA} | Lookback: {NEWS_LOOKBACK_DAYS} days")

# ============================================================
# CELL 3: Labeled Benchmark Dataset
# ============================================================
# A curated set of Indian financial headlines with ground-truth
# category and sentiment labels. Used in Cells 4 and 4.5 to
# produce real accuracy numbers instead of guessing from 5 headlines.

LABELED_BENCHMARK = [
    # Earnings & Output (6)
    {"text": "Infosys reports 18% jump in Q2 net profit, beats Street estimates on strong deal wins",              "category": "Earnings & Output",   "sentiment": "positive"},
    {"text": "TCS quarterly revenue misses analyst forecasts, citing weak BFSI demand in the US",                   "category": "Earnings & Output",   "sentiment": "negative"},
    {"text": "Reliance Industries posts record quarterly profits driven by O2C and Jio segments",                   "category": "Earnings & Output",   "sentiment": "positive"},
    {"text": "Wipro Q3 results disappoint as IT major reports revenue decline for second consecutive quarter",       "category": "Earnings & Output",   "sentiment": "negative"},
    {"text": "HDFC Bank reports 20% growth in net interest income; asset quality remains stable",                   "category": "Earnings & Output",   "sentiment": "positive"},
    {"text": "Sun Pharma Q1 earnings in-line with estimates; US generics business shows muted growth",              "category": "Earnings & Output",   "sentiment": "neutral"},
    # Analyst Ratings (5)
    {"text": "Goldman Sachs upgrades Zomato to Buy, raises target price to Rs 280",                                 "category": "Analyst Ratings",     "sentiment": "positive"},
    {"text": "Morgan Stanley downgrades Maruti Suzuki to Underweight citing rural demand slowdown",                 "category": "Analyst Ratings",     "sentiment": "negative"},
    {"text": "Citi initiates coverage on DLF with Neutral rating, expects limited upside near term",               "category": "Analyst Ratings",     "sentiment": "neutral"},
    {"text": "CLSA upgrades Axis Bank to Outperform with a 25% upside target price",                               "category": "Analyst Ratings",     "sentiment": "positive"},
    {"text": "Macquarie cuts Bajaj Finance target price, warns of rising credit costs ahead",                       "category": "Analyst Ratings",     "sentiment": "negative"},
    # Market Action (5)
    {"text": "Sensex surges 800 points as FII inflows hit monthly high on dovish Fed signals",                     "category": "Market Action",       "sentiment": "positive"},
    {"text": "Nifty 50 falls 1.2% as global sell-off triggers broad-based decline in Indian equities",             "category": "Market Action",       "sentiment": "negative"},
    {"text": "HDFC Bank shares hit 52-week high after strong Q2 results and positive management commentary",       "category": "Market Action",       "sentiment": "positive"},
    {"text": "Adani Group stocks crash as short-seller report triggers widespread panic selling",                   "category": "Market Action",       "sentiment": "negative"},
    {"text": "IT stocks trade range-bound ahead of US CPI data release this week",                                  "category": "Market Action",       "sentiment": "neutral"},
    # Deals & Acquisitions (4)
    {"text": "Tata Motors acquires British EV startup for $200 million to strengthen clean mobility portfolio",     "category": "Deals & Acquisitions","sentiment": "positive"},
    {"text": "HDFC Life completes acquisition of Exide Life Insurance for Rs 6,687 crore",                         "category": "Deals & Acquisitions","sentiment": "positive"},
    {"text": "Reliance abandons proposed acquisition of Future Retail after lengthy legal battle",                  "category": "Deals & Acquisitions","sentiment": "negative"},
    {"text": "Merger between two mid-cap banks gets final regulatory approval from RBI",                            "category": "Deals & Acquisitions","sentiment": "positive"},
    # Macro & Policy (6)
    {"text": "RBI keeps repo rate unchanged at 6.5%, signals cautious approach to rate cuts",                      "category": "Macro & Policy",      "sentiment": "neutral"},
    {"text": "India GDP growth accelerates to 8.4% in Q3, beats IMF forecast comfortably",                         "category": "Macro & Policy",      "sentiment": "positive"},
    {"text": "SEBI tightens F&O regulations, raises contract sizes to curb retail speculation",                     "category": "Macro & Policy",      "sentiment": "negative"},
    {"text": "Government announces PLI scheme expansion for semiconductors worth Rs 76,000 crore",                  "category": "Macro & Policy",      "sentiment": "positive"},
    {"text": "RBI imposes Rs 2 crore penalty on major bank for non-compliance with KYC norms",                      "category": "Macro & Policy",      "sentiment": "negative"},
    {"text": "Union Budget raises capital gains tax on equities from 10% to 12.5%",                                 "category": "Macro & Policy",      "sentiment": "negative"},
    # Other (3)
    {"text": "NSE extends trading hours to 5 PM for equity derivatives segment from next month",                    "category": "Other",               "sentiment": "neutral"},
    {"text": "India becomes world's fourth largest stock market by total market capitalization",                    "category": "Other",               "sentiment": "positive"},
    {"text": "BSE introduces new risk management framework for the SME IPO segment",                               "category": "Other",               "sentiment": "neutral"},
]

df_benchmark = pd.DataFrame(LABELED_BENCHMARK)
SENT_LABEL_MAP = {"positive": 1, "negative": -1, "neutral": 0}
df_benchmark['sentiment_score'] = df_benchmark['sentiment'].map(SENT_LABEL_MAP)

print(f"✅ Labeled Benchmark Ready: {len(df_benchmark)} headlines")
print("\nCategory distribution:")
print(df_benchmark['category'].value_counts().to_string())
print("\nSentiment distribution:")
print(df_benchmark['sentiment'].value_counts().to_string())

# ============================================================
# CELL 4: Categorization Head-to-Head — BART vs Mistral
#   Uses the labeled benchmark (Cell 3) for real accuracy numbers.
#   VRAM budget: BART ~1.6 GB + Mistral 4-bit ~4.5 GB = ~6.1 GB peak
#   Mistral is deleted after this cell; BART stays for the whole session.
# ============================================================

def scrub_vram(*var_names):
    """Delete named GPU-resident objects and clear CUDA cache."""
    frame = __import__('sys')._getframe(1).f_locals  # caller's locals  (fallback)
    for v in var_names:
        if v in globals():
            del globals()[v]
    gc.collect()
    torch.cuda.empty_cache()
    print(f"🧹 VRAM after scrub: {torch.cuda.memory_allocated()/1024**3:.2f} GB")

# ── PHASE 1: BART ─────────────────────────────────────────
print("=" * 55)
print("PHASE 1 — Loading facebook/bart-large-mnli (BART)")
print("=" * 55)

bart_pipe = pipeline(
    "zero-shot-classification",
    model="facebook/bart-large-mnli",
    device=0 if device == "cuda" else -1
)

def bart_categorize(text: str) -> str:
    result = bart_pipe(text[:512], VALID_CATEGORIES, multi_label=False)
    return result['labels'][0]

texts_bench = df_benchmark['text'].tolist()
true_cats   = df_benchmark['category'].tolist()

print("Running BART on benchmark...")
t0 = time.time()
bart_preds = [bart_categorize(t) for t in texts_bench]
bart_cat_time = time.time() - t0
bart_cat_acc  = accuracy_score(true_cats, bart_preds)
bart_cat_f1   = f1_score(true_cats, bart_preds, average='macro', zero_division=0)

print(f"✅ BART | Acc: {bart_cat_acc*100:.1f}% | F1: {bart_cat_f1:.3f} | Time: {bart_cat_time:.1f}s")

# ── PHASE 2: Mistral / Zephyr-7B ─────────────────────────
print("\n" + "=" * 55)
print("PHASE 2 — Loading Zephyr-7B-Beta (Mistral, 4-bit)")
print("=" * 55)

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16
)
_z_tok   = AutoTokenizer.from_pretrained("HuggingFaceH4/zephyr-7b-beta", token=hf_token)
_z_model = AutoModelForCausalLM.from_pretrained(
    "HuggingFaceH4/zephyr-7b-beta",
    quantization_config=bnb_config,
    device_map="auto",
    token=hf_token
)
mistral_pipe = pipeline(
    "text-generation", model=_z_model, tokenizer=_z_tok, batch_size=4
)

CAT_LIST_STR = ", ".join(VALID_CATEGORIES)
def mistral_categorize(text: str) -> str:
    prompt = (
        f"<|system|>You are a precise financial news classifier.</s>\n"
        f"<|user|>Classify this headline into EXACTLY ONE of these categories: {CAT_LIST_STR}.\n"
        f"Headline: \"{text}\"\nRespond with the category name only.</s>\n<|assistant|>"
    )
    out = mistral_pipe(prompt, max_new_tokens=15, temperature=0.05,
                       return_full_text=False)[0]['generated_text'].strip()
    for cat in VALID_CATEGORIES:
        if cat.lower() in out.lower():
            return cat
    return "Other"

print("Running Mistral on benchmark...")
t0 = time.time()
mistral_preds    = [mistral_categorize(t) for t in texts_bench]
mistral_cat_time = time.time() - t0
mistral_cat_acc  = accuracy_score(true_cats, mistral_preds)
mistral_cat_f1   = f1_score(true_cats, mistral_preds, average='macro', zero_division=0)

print(f"✅ Mistral | Acc: {mistral_cat_acc*100:.1f}% | F1: {mistral_cat_f1:.3f} | Time: {mistral_cat_time:.1f}s")

# Free Mistral — BART stays active for Cells 5-9
scrub_vram('_z_tok', '_z_model', 'mistral_pipe')

# ── Results & Plots ───────────────────────────────────────
print("\n" + "=" * 55)
print("CATEGORIZATION BENCHMARK RESULTS")
print("=" * 55)
comparison_df = pd.DataFrame({
    'Headline': [t[:55] + '...' for t in texts_bench],
    'True Category': true_cats,
    'BART': bart_preds,
    'Mistral': mistral_preds
})
display(HTML(comparison_df.to_html(index=False)))

fig, axes = plt.subplots(1, 3, figsize=(15, 5))
models_lbl = ['BART-Large', 'Mistral-7B']
sns.barplot(x=models_lbl, y=[bart_cat_time, mistral_cat_time], ax=axes[0], palette='Reds_d')
axes[0].set_title('Inference Time (s) — Lower is Better')
axes[0].set_ylabel('Seconds')
sns.barplot(x=models_lbl, y=[bart_cat_acc*100, mistral_cat_acc*100], ax=axes[1], palette='Greens_d')
axes[1].set_title('Accuracy (%) — Higher is Better'); axes[1].set_ylim(0, 105)
sns.barplot(x=models_lbl, y=[bart_cat_f1, mistral_cat_f1], ax=axes[2], palette='Blues_d')
axes[2].set_title('Macro F1 — Higher is Better'); axes[2].set_ylim(0, 1.05)
plt.tight_layout(); plt.show()

# Both are kept for the UI (Cell 10). BART is the fast default.
categorize_news = bart_categorize
print("\n✅ Global categorizer → BART (fast; Mistral reloaded in Cell 9.8 for UI comparison)")

# ============================================================
# CELL 4.5: Sentiment Model Benchmark — FinBERT vs DistilRoBERTa-Financial
#   Both models fit comfortably alongside BART in VRAM.
#   VRAM budget: BART 1.6 GB + FinBERT 0.45 GB + DistilRoBERTa 0.27 GB ≈ 2.3 GB
#   The losing model is deleted; winner becomes `active_sentiment_pipe`.
# ============================================================

def normalize_sentiment(label: str) -> int:
    """Map any model's label convention to +1 / 0 / -1."""
    l = label.lower()
    if l in ('positive', 'pos', 'label_2'): return  1
    if l in ('negative', 'neg', 'label_0'): return -1
    return 0

def evaluate_sentiment_pipe(pipe_fn, texts, true_labels):
    """Run a sentiment pipeline and return (preds, confidences, elapsed, accuracy, f1)."""
    preds, confs = [], []
    t0 = time.time()
    for text in texts:
        result = pipe_fn(text[:512])[0]
        preds.append(normalize_sentiment(result['label']))
        confs.append(result['score'])
    elapsed = time.time() - t0
    acc = accuracy_score(true_labels, preds)
    f1  = f1_score(true_labels, preds, average='macro', zero_division=0)
    return preds, confs, elapsed, acc, f1

print("=" * 55)
print("SENTIMENT MODEL BENCHMARK")
print("=" * 55)

true_sents   = df_benchmark['sentiment_score'].tolist()
bench_texts  = df_benchmark['text'].tolist()

# ── FinBERT ───────────────────────────────────────────────
print("\nLoading ProsusAI/finbert...")
finbert_pipe = pipeline(
    "sentiment-analysis",
    model="ProsusAI/finbert",
    device=0 if device == "cuda" else -1
)
fb_preds, fb_confs, fb_time, fb_acc, fb_f1 = evaluate_sentiment_pipe(
    finbert_pipe, bench_texts, true_sents
)
print(f"✅ FinBERT       | Acc: {fb_acc*100:.1f}% | F1: {fb_f1:.3f} | Avg Conf: {np.mean(fb_confs):.3f} | Time: {fb_time:.2f}s")

# ── DistilRoBERTa-Financial ───────────────────────────────
print("Loading mrm8488/distilroberta-finetuned-financial-news-sentiment-analysis...")
distilrob_pipe = pipeline(
    "sentiment-analysis",
    model="mrm8488/distilroberta-finetuned-financial-news-sentiment-analysis",
    device=0 if device == "cuda" else -1
)
dr_preds, dr_confs, dr_time, dr_acc, dr_f1 = evaluate_sentiment_pipe(
    distilrob_pipe, bench_texts, true_sents
)
print(f"✅ DistilRoBERTa | Acc: {dr_acc*100:.1f}% | F1: {dr_f1:.3f} | Avg Conf: {np.mean(dr_confs):.3f} | Time: {dr_time:.2f}s")

# ── Plot ──────────────────────────────────────────────────
fig, axes = plt.subplots(1, 3, figsize=(15, 5))
model_lbl = ['FinBERT', 'DistilRoBERTa']
sns.barplot(x=model_lbl, y=[fb_acc*100, dr_acc*100], ax=axes[0], palette='Greens_d')
axes[0].set_title('Accuracy (%)'); axes[0].set_ylim(0, 105)
sns.barplot(x=model_lbl, y=[fb_f1, dr_f1], ax=axes[1], palette='Blues_d')
axes[1].set_title('Macro F1'); axes[1].set_ylim(0, 1.05)
sns.barplot(x=model_lbl, y=[fb_time, dr_time], ax=axes[2], palette='Reds_d')
axes[2].set_title('Inference Time (s) — Lower is Better')
plt.tight_layout(); plt.show()

# ── Select Winner ─────────────────────────────────────────
# Primary criterion: accuracy. Tiebreak: speed.
if fb_acc > dr_acc or (fb_acc == dr_acc and fb_time <= dr_time):
    SENTIMENT_MODEL_NAME  = "ProsusAI/finbert"
    active_sentiment_pipe = finbert_pipe
    scrub_vram('distilrob_pipe')
    print(f"\n✅ Winner → FinBERT (Acc: {fb_acc*100:.1f}%)")
else:
    SENTIMENT_MODEL_NAME  = "mrm8488/distilroberta-finetuned-financial-news-sentiment-analysis"
    active_sentiment_pipe = distilrob_pipe
    scrub_vram('finbert_pipe')
    print(f"\n✅ Winner → DistilRoBERTa-Financial (Acc: {dr_acc*100:.1f}%)")

print(f"   Model saved as global `active_sentiment_pipe`")

# ============================================================
# CELL 5: Final NLP Pipeline Activation
#   Sets up the two production functions used everywhere:
#     get_clean_sentiment(text) → (val: int, conf: float)
#     categorize_news(text)     → category string
# ============================================================

BULLISH_KEYWORDS = [
    "buy", "strong buy", "upgrade", "bullish", "surge", "rally", "soar",
    "record", "beat", "beats", "outperform", "positive", "growth", "win"
]
BEARISH_KEYWORDS = [
    "sell", "strong sell", "downgrade", "bearish", "drop", "crash",
    "plunge", "slump", "loss", "losses", "penalty", "fraud", "default",
    "miss", "misses", "decline", "warning", "cut", "disappoints"
]

def get_clean_sentiment(text: str):
    """
    Returns (sentiment_value: int, confidence: float)
    where sentiment_value ∈ {-1, 0, 1}.
    Applies domain keyword overrides for high-signal financial terms
    before falling back to the NLP model.
    """
    text_lower = text.lower()

    # Hard keyword overrides (high precision for clear financial signals)
    if any(w in text_lower for w in BEARISH_KEYWORDS):
        model_result = active_sentiment_pipe(text[:512])[0]
        model_label  = normalize_sentiment(model_result['label'])
        # Only override if model also agrees or is neutral (avoid false negatives)
        if model_label <= 0:
            return -1, max(model_result['score'], 0.88)

    if any(w in text_lower for w in BULLISH_KEYWORDS):
        model_result = active_sentiment_pipe(text[:512])[0]
        model_label  = normalize_sentiment(model_result['label'])
        if model_label >= 0:
            return 1, max(model_result['score'], 0.88)

    # Pure model output
    result = active_sentiment_pipe(text[:512])[0]
    return normalize_sentiment(result['label']), result['score']

print("✅ NLP Pipelines Active")
print(f"   Sentiment model : {SENTIMENT_MODEL_NAME}")
print(f"   Categorization  : facebook/bart-large-mnli")
print(f"   VRAM in use     : {torch.cuda.memory_allocated()/1024**3:.2f} GB")

# Quick sanity check
_test = "Infosys beats revenue estimates with strong deal wins"
_sv, _sc = get_clean_sentiment(_test)
_cat = categorize_news(_test)
print(f"\nSanity check: '{_test[:50]}...'")
print(f"  Sentiment: {_sv:+d} (conf: {_sc:.2f}) | Category: {_cat}")

# ============================================================
# CELL 6: Feature Engineering
#   Three key improvements over the original:
#   1. Multi-category encoding: every category gets its own
#      sentiment column per day — no signal lost to mode-collapse.
#   2. Time-decay weighting: exponential decay on news recency.
#   3. Noise-filtered binary target: flat days removed.
# ============================================================

def build_daily_features(df_news_raw: pd.DataFrame,
                          trading_dates: pd.DatetimeIndex,
                          decay_lambda: float = DECAY_LAMBDA,
                          lookback_days: int   = NEWS_LOOKBACK_DAYS) -> pd.DataFrame:
    """
    For each trading date, builds a 12-column feature row:
      - Sentiment_{cat}: time-decay & confidence-weighted mean sentiment
        for all headlines in that category within the lookback window.
      - Count_{cat}: number of articles contributing to that category.

    Because every category gets its own column, a day with 3 Macro
    headlines AND 2 Earnings headlines produces meaningful values in
    BOTH columns — the original mode-collapse bug is eliminated.
    """
    rows = []
    df_news_raw = df_news_raw.copy()
    df_news_raw['date'] = pd.to_datetime(df_news_raw['date'])

    for tdate in trading_dates:
        window_start = tdate - pd.Timedelta(days=lookback_days)
        window = df_news_raw[
            (df_news_raw['date'] >= window_start) &
            (df_news_raw['date'] <= tdate)
        ].copy()

        row = {'Date': tdate}
        for cat in VALID_CATEGORIES:
            cat_df = window[window['category'] == cat].copy()
            if cat_df.empty:
                row[f"Sentiment_{cat}"] = 0.0
                row[f"Count_{cat}"]     = 0
                continue

            # Time decay: e^(-λ * days_ago)
            cat_df['days_ago']     = (tdate - cat_df['date']).dt.days
            cat_df['time_weight']  = np.exp(-decay_lambda * cat_df['days_ago'])
            cat_df['eff_weight']   = cat_df['sentiment_conf'] * cat_df['time_weight']

            total_w = cat_df['eff_weight'].sum()
            weighted_sent = (
                (cat_df['sentiment_val'] * cat_df['eff_weight']).sum() / total_w
                if total_w > 0 else 0.0
            )
            row[f"Sentiment_{cat}"] = weighted_sent
            row[f"Count_{cat}"]     = len(cat_df)

        rows.append(row)

    df_out = pd.DataFrame(rows).set_index('Date')
    df_out.index = pd.to_datetime(df_out.index).tz_localize(None)
    return df_out


def make_stock_target(ticker: str, start: str, end: str,
                      threshold: float = RETURN_THRESHOLD):
    """
    Download OHLCV, compute next-day return, apply noise filter.
    Returns df_stock with 'Target' column (1 = up, 0 = down).
    Flat days (|return| < threshold) are DROPPED — they are noise.
    """
    df = yf.download(ticker, start=start, end=end, progress=False)
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = df.columns.get_level_values(0)
    df.index = pd.to_datetime(df.index).tz_localize(None)

    returns = df['Close'].pct_change().shift(-1)
    df['Return'] = returns
    df['Target'] = np.where(
        returns >  threshold, 1,
        np.where(returns < -threshold, 0, np.nan)
    )
    before = len(df)
    df = df.dropna(subset=['Target'])
    df['Target'] = df['Target'].astype(int)
    print(f"  Noise filter ({ticker}): kept {len(df)}/{before} days "
          f"(removed {before - len(df)} flat days ≤ ±{threshold*100:.1f}%)")
    return df


# ── Mock data pipeline test ───────────────────────────────
import yfinance as yf

mock_news = {
    'date': ['2023-10-25','2023-10-26','2023-10-26',
             '2023-10-27','2023-10-30','2023-10-30','2023-10-31'],
    'headline': [
        "The central bank announces a new monetary policy, keeping interest rates steady.",
        "Tech giant TCS reports stellar Q3 results, beating all revenue estimates.",
        "Goldman Sachs upgrades TCS to Buy with a Rs 4,200 target price.",
        "Upcoming elections cause market uncertainty among major investors.",
        "Government proposes a new budget with heavy tech subsidies.",
        "Markets surge on strong FII inflows and positive global cues.",
        "Supply chain disruptions lead to terrible quarterly results for manufacturing.",
    ]
}
df_mock_news = pd.DataFrame(mock_news)
df_mock_news['date'] = pd.to_datetime(df_mock_news['date'])

print("Analyzing mock headlines...")
df_mock_news['sentiment_val']  = df_mock_news['headline'].apply(lambda h: get_clean_sentiment(h)[0])
df_mock_news['sentiment_conf'] = df_mock_news['headline'].apply(lambda h: get_clean_sentiment(h)[1])
df_mock_news['category']       = df_mock_news['headline'].apply(categorize_news)
print(df_mock_news[['date','category','sentiment_val']].to_string())

df_spy = make_stock_target("SPY", "2023-10-20", "2023-11-05")
df_feat_mock = build_daily_features(df_mock_news, df_spy.index)
df_merged_mock = df_spy.merge(df_feat_mock, left_index=True, right_index=True, how='left').fillna(0)

X_mock = df_merged_mock[ALL_FEATURES].astype('float32')
y_mock = df_merged_mock['Target'].astype('int')

print(f"\n✅ Mock feature matrix: {X_mock.shape}")
print(f"   Target distribution: {dict(y_mock.value_counts())}")
print(f"   Multi-category check (non-zero columns per row):")
print((X_mock[SENTIMENT_FEATURES] != 0).sum(axis=1).describe().to_string())

# ============================================================
# CELL 7: Walk-Forward Validation + Stacking Ensemble
#   Walk-forward prevents look-ahead bias for time-series data.
#   Stacking: base models produce out-of-fold (OOF) probability
#   predictions, which a meta-model (LogReg) learns to combine.
#
#   NOTE: With tiny mock data these numbers are illustrative.
#   Run Cell 9 to collect real data, then re-run Cell 8 for
#   meaningful performance metrics.
# ============================================================
from IPython.display import display, clear_output, HTML

def walk_forward_oof(models_dict: dict, X: pd.DataFrame,
                     y: pd.Series, n_splits: int = 5):
    """
    Time-series walk-forward cross-validation.
    Returns:
      fold_results_df : per-fold accuracy table
      oof_probs       : dict of model_name → full-length OOF probability array
    """
    # Auto-cap splits to avoid empty folds on small datasets
    n = max(2, min(n_splits, len(X) // 3))
    tscv = TimeSeriesSplit(n_splits=n)

    oof_probs    = {name: np.full(len(X), np.nan) for name in models_dict}
    fold_records = []

    for fold_i, (tr_idx, te_idx) in enumerate(tscv.split(X), start=1):
        # Skip folds where training data has only one class
        if len(np.unique(y.iloc[tr_idx])) < 2:
            print(f"  Fold {fold_i}: skipped (single class in training)")
            continue

        X_tr, X_te = X.iloc[tr_idx], X.iloc[te_idx]
        y_tr, y_te = y.iloc[tr_idx], y.iloc[te_idx]
        record = {'Fold': fold_i, 'Train': len(X_tr), 'Test': len(X_te)}

        for name, mdl in models_dict.items():
            mdl.fit(X_tr, y_tr)
            prob = mdl.predict_proba(X_te)[:, 1]
            oof_probs[name][te_idx] = prob
            record[f'{name}_Acc'] = accuracy_score(y_te, (prob > 0.5).astype(int))

        fold_records.append(record)

    return pd.DataFrame(fold_records), oof_probs


def build_stacking_meta(oof_probs: dict, y: pd.Series):
    """
    Train a LogisticRegression meta-model on OOF probability matrix.
    Returns trained meta-model (or None if insufficient data).
    """
    oof_matrix = np.column_stack([oof_probs[n] for n in oof_probs])
    valid      = ~np.isnan(oof_matrix).any(axis=1)

    if valid.sum() < 10:
        print("⚠️  Too few OOF samples for stacking. Run Cell 9 for real data.")
        return None

    X_meta = oof_matrix[valid]
    y_meta = y.values[valid]

    meta = LogisticRegression(random_state=42, max_iter=300, C=1.0)
    meta.fit(X_meta, y_meta)

    meta_preds = (meta.predict_proba(X_meta)[:, 1] > 0.5).astype(int)
    print(f"  Meta-model trained on {valid.sum()} OOF samples")
    print(f"  Meta-accuracy (in-sample): {accuracy_score(y_meta, meta_preds)*100:.1f}%")
    print(f"  Base model weights: { {n: round(w,3) for n,w in zip(oof_probs.keys(), meta.coef_[0])} }")
    return meta


BASE_MODELS = {
    "LogReg":       LogisticRegression(random_state=42, max_iter=500),
    "RandomForest": RandomForestClassifier(n_estimators=100, random_state=42),
    "XGBoost":      XGBClassifier(eval_metric='logloss', random_state=42, verbosity=0),
    "LightGBM":     lgb.LGBMClassifier(random_state=42, verbose=-1),
}

print("Running Walk-Forward Validation on mock data...")
fold_df_mock, oof_mock = walk_forward_oof(BASE_MODELS, X_mock, y_mock, n_splits=5)
print("\nPer-Fold Results:")
display(fold_df_mock)

print("\nBuilding Stacking Meta-Model...")
stacker_mock = build_stacking_meta(oof_mock, y_mock)

# Retrain base models on full mock data for downstream cells
trained_models = {}
for name, mdl in BASE_MODELS.items():
    if len(np.unique(y_mock)) >= 2:
        mdl.fit(X_mock, y_mock)
    trained_models[name] = mdl

print("\n✅ Walk-Forward + Stacking proof-of-concept complete.")
print("   Run Cell 9 → Cell 9.5 → Cell 8 for production results.")

# ============================================================
# CELL 8: Full Walk-Forward Evaluation
#   Re-run this AFTER Cell 9 has populated the master CSV.
#   Uses the same walk_forward_oof() function from Cell 7.
# ============================================================
import yfinance as yf  # noqa: re-import is harmless

if not os.path.exists(CSV_FILENAME):
    print("⚠️  Master CSV not found.")
    print("   Please run Cell 9 first, then re-run this cell.")
    print("   (Showing mock-data metrics as placeholder...)\n")
    df_eval_src = df_merged_mock.copy()
else:
    print(f"📂 Loading master data from {CSV_FILENAME}...")
    df_eval_src = pd.read_csv(CSV_FILENAME, index_col=0)
    print(f"   Loaded {len(df_eval_src)} rows across "
          f"{df_eval_src['Ticker'].nunique() if 'Ticker' in df_eval_src.columns else '?'} tickers")

# Ensure feature columns exist and are numeric
for col in ALL_FEATURES:
    if col not in df_eval_src.columns:
        df_eval_src[col] = 0.0
    df_eval_src[col] = pd.to_numeric(df_eval_src[col], errors='coerce').fillna(0)

df_eval_src['Target'] = pd.to_numeric(df_eval_src['Target'], errors='coerce')
df_eval_src = df_eval_src.dropna(subset=['Target'])
df_eval_src['Target'] = df_eval_src['Target'].astype(int)

X_eval = df_eval_src[ALL_FEATURES].astype('float32')
y_eval = df_eval_src['Target'].astype('int')

print(f"\nEvaluation set: {len(X_eval)} samples | "
      f"Class balance: {dict(y_eval.value_counts())}")

EVAL_MODELS = {
    "LogReg":       LogisticRegression(random_state=42, max_iter=500),
    "RandomForest": RandomForestClassifier(n_estimators=100, random_state=42),
    "XGBoost":      XGBClassifier(eval_metric='logloss', random_state=42, verbosity=0),
    "LightGBM":     lgb.LGBMClassifier(random_state=42, verbose=-1),
}

print("\nRunning Walk-Forward Evaluation...")
fold_df_eval, oof_eval = walk_forward_oof(EVAL_MODELS, X_eval, y_eval, n_splits=5)
print("\nPer-Fold Accuracy:")
display(fold_df_eval)

# Mean metrics across folds
acc_cols = [c for c in fold_df_eval.columns if '_Acc' in c]
mean_accs = fold_df_eval[acc_cols].mean()
print("\n=== MEAN WALK-FORWARD ACCURACY ===")
results_eval = []
for col, val in mean_accs.items():
    name = col.replace('_Acc', '')
    print(f"  {name:<18}: {val*100:.1f}%")
    results_eval.append({'Model': name, 'Mean_Accuracy': val * 100})

df_eval_results = pd.DataFrame(results_eval).sort_values('Mean_Accuracy', ascending=False)

plt.figure(figsize=(10, 5))
sns.barplot(data=df_eval_results, x='Model', y='Mean_Accuracy', palette='viridis')
plt.axhline(50, color='red', linestyle='--', label='Random Baseline (50%)')
plt.title('Walk-Forward Mean Accuracy by Model (Real Data)')
plt.ylabel('Accuracy (%)'); plt.ylim(0, 105); plt.legend()
plt.show()

print("\nNote: Sustained accuracy > 55% is meaningful in financial sentiment ML.")
print("      Accuracy > 60% is strong. Evaluate on out-of-sample periods too.")

# ============================================================
# CELL 9: Batch Data Collection — All 50 Nifty Companies
#   Improvements vs original:
#   ✅ Multi-category feature encoding (no signal loss)
#   ✅ Time-decay weighting
#   ✅ Noise-filtered binary target
#   ✅ Article body extraction via trafilatura
#   ✅ Hindi regional news + Google Translate
#   ✅ CSV checkpointing — safe to interrupt and resume
#   ✅ GNews retry with exponential back-off + freshness filter
#   ✅ Fallback search query if primary returns nothing
# ============================================================
import yfinance as yf  # noqa

NIFTY_50_CONFIG = {
    "RELIANCE.NS":   {"full": "Reliance Industries",         "exclude": ["Power", "Infrastructure"]},
    "TCS.NS":        {"full": "Tata Consultancy Services",   "exclude": []},
    "HDFCBANK.NS":   {"full": "HDFC Bank",                   "exclude": ["Life", "AMC"]},
    "ICICIBANK.NS":  {"full": "ICICI Bank",                  "exclude": ["Prudential", "Lombard"]},
    "INFY.NS":       {"full": "Infosys",                     "exclude": []},
    "SBIN.NS":       {"full": "State Bank of India",         "exclude": ["Cards", "Life"]},
    "BHARTIARTL.NS": {"full": "Bharti Airtel",               "exclude": []},
    "ITC.NS":        {"full": "ITC Limited",                 "exclude": []},
    "LT.NS":         {"full": "Larsen Toubro",               "exclude": ["Infotech", "Finance"]},
    "BAJFINANCE.NS": {"full": "Bajaj Finance",               "exclude": ["Finserv"]},
    "AXISBANK.NS":   {"full": "Axis Bank",                   "exclude": ["AMC"]},
    "HINDUNILVR.NS": {"full": "Hindustan Unilever",          "exclude": []},
    "KOTAKBANK.NS":  {"full": "Kotak Mahindra Bank",         "exclude": []},
    "TATAMOTORS.NS": {"full": "Tata Motors",                 "exclude": ["Steel", "Power", "Chemicals"]},
    "SUNPHARMA.NS":  {"full": "Sun Pharmaceutical",          "exclude": []},
    "TITAN.NS":      {"full": "Titan Company",               "exclude": []},
    "MARUTI.NS":     {"full": "Maruti Suzuki",               "exclude": []},
    "NTPC.NS":       {"full": "NTPC Limited",                "exclude": []},
    "TATASTEEL.NS":  {"full": "Tata Steel",                  "exclude": ["Motors", "Power"]},
    "ULTRACEMCO.NS": {"full": "UltraTech Cement",            "exclude": []},
    "POWERGRID.NS":  {"full": "Power Grid Corporation",      "exclude": []},
    "M&M.NS":        {"full": "Mahindra Mahindra",           "exclude": ["Finance", "Holidays"]},
    "BAJAJFINSV.NS": {"full": "Bajaj Finserv",               "exclude": ["Finance"]},
    "ASIANPAINT.NS": {"full": "Asian Paints",                "exclude": []},
    "COALINDIA.NS":  {"full": "Coal India",                  "exclude": []},
    "ONGC.NS":       {"full": "ONGC",                        "exclude": []},
    "ADANIPORTS.NS": {"full": "Adani Ports",                 "exclude": ["Power", "Green", "Gas"]},
    "ADANIENT.NS":   {"full": "Adani Enterprises",           "exclude": ["Ports", "Green"]},
    "HCLTECH.NS":    {"full": "HCL Technologies",            "exclude": []},
    "WIPRO.NS":      {"full": "Wipro",                       "exclude": []},
    "HAL.NS":        {"full": "Hindustan Aeronautics",       "exclude": []},
    "DLF.NS":        {"full": "DLF Limited",                 "exclude": []},
    "TRENT.NS":      {"full": "Trent Limited",               "exclude": []},
    "ZOMATO.NS":     {"full": "Zomato",                      "exclude": []},
    "DMART.NS":      {"full": "Avenue Supermarts",           "exclude": []},
    "VBL.NS":        {"full": "Varun Beverages",             "exclude": []},
    "DRREDDY.NS":    {"full": "Dr Reddys Laboratories",      "exclude": []},
    "JSWSTEEL.NS":   {"full": "JSW Steel",                   "exclude": ["Energy", "Infrastructure"]},
    "GRASIM.NS":     {"full": "Grasim Industries",           "exclude": []},
    "INDUSINDBK.NS": {"full": "IndusInd Bank",               "exclude": []},
    "LTIM.NS":       {"full": "LTIMindtree",                 "exclude": []},
    "RECLTD.NS":     {"full": "REC Limited",                 "exclude": []},
    "PFC.NS":        {"full": "Power Finance Corporation",   "exclude": []},
    "BEL.NS":        {"full": "Bharat Electronics",          "exclude": []},
    "EICHERMOT.NS":  {"full": "Eicher Motors",               "exclude": []},
    "BAJAJ-AUTO.NS": {"full": "Bajaj Auto",                  "exclude": ["Finance", "Finserv"]},
    "DIVISLAB.NS":   {"full": "Divis Laboratories",          "exclude": []},
    "APOLLOHOSP.NS": {"full": "Apollo Hospitals",            "exclude": ["Tyres"]},
    "TECHM.NS":      {"full": "Tech Mahindra",               "exclude": []},
    "CIPLA.NS":      {"full": "Cipla",                       "exclude": []},
}

# ── Helper: Article Body Extraction ───────────────────────
_REQ_HEADERS = {
    'User-Agent': (
        'Mozilla/5.0 (Windows NT 10.0; Win64; x64) '
        'AppleWebKit/537.36 (KHTML, like Gecko) '
        'Chrome/120.0.0.0 Safari/537.36'
    )
}

def fetch_article_body(url: str, char_limit: int = 1500) -> str | None:
    """
    Extract article body using trafilatura.
    Returns first `char_limit` chars, or None on failure.
    Falls back gracefully — headline analysis continues regardless.
    """
    if not url:
        return None
    try:
        resp = requests.get(url, headers=_REQ_HEADERS, timeout=8, verify=False)
        if resp.status_code == 200:
            body = trafilatura.extract(
                resp.text,
                include_comments=False,
                include_tables=False,
                favor_recall=True
            )
            if body and len(body) > 120:
                return body[:char_limit]
    except Exception:
        pass
    return None


# ── Helper: Translation ────────────────────────────────────
_translator_hi = GoogleTranslator(source='hi', target='en')

def translate_to_english(text: str, source_lang: str = 'hi'):
    """
    Translate text from regional language to English.
    Returns (translated_text, was_translated: bool).
    """
    try:
        time.sleep(0.4)  # Respect free-tier rate limits
        if source_lang == 'hi':
            result = _translator_hi.translate(text[:450])
        else:
            result = GoogleTranslator(source=source_lang, target='en').translate(text[:450])
        if result and result.strip() and result != text:
            return result.strip(), True
    except Exception:
        pass
    return text, False


# ── Helper: Robust GNews Fetch ────────────────────────────
def fetch_news_robust(company_name: str, start_d: datetime.date,
                      end_d: datetime.date, language: str = 'en',
                      max_retries: int = 3) -> list:
    """
    Fetch news with:
    - Exponential back-off retries
    - Freshness filter (reject articles older than 35 days)
    - Fallback query (shorter company name) if primary returns nothing
    """
    sd = (start_d.year, start_d.month, start_d.day)
    ed = (end_d.year,   end_d.month,   end_d.day)

    suffix_en = " stock NSE"
    suffix_hi = " शेयर बाजार"
    suffix    = suffix_hi if language == 'hi' else suffix_en

    queries = [
        urllib.parse.quote(company_name + suffix),
        urllib.parse.quote(company_name),             # Fallback: bare name
    ]

    max_days_old = 35

    for query in queries:
        for attempt in range(max_retries):
            try:
                time.sleep(1.5 + attempt * 2.0)
                gn = GNews(language=language, country='IN',
                           max_results=25, start_date=sd, end_date=ed)
                items = gn.get_news(query)

                if not items:
                    continue

                fresh = []
                for item in items:
                    try:
                        pub = pd.to_datetime(item['published date'])
                        if pub.tzinfo:
                            pub = pub.tz_localize(None)
                        # Sanity check: reject obviously wrong dates
                        if pub.year < 2020:
                            continue
                        if (datetime.datetime.now() - pub).days <= max_days_old:
                            fresh.append(item)
                    except Exception:
                        pass

                if fresh:
                    return fresh

            except Exception as e:
                wait = 5 * (attempt + 1)
                print(f"    ⚠️  Attempt {attempt+1} failed ({str(e)[:40]}). Retrying in {wait}s...")
                time.sleep(wait)

    return []  # All retries exhausted


# ── Checkpointing: discover already-processed tickers ─────
processed_tickers: set = set()
if os.path.exists(CSV_FILENAME):
    try:
        _existing = pd.read_csv(CSV_FILENAME, usecols=['Ticker'])
        processed_tickers = set(_existing['Ticker'].unique())
        print(f"📂 Found existing database ({len(processed_tickers)} tickers processed).")
        print(f"   Resuming from checkpoint. Skipping: {sorted(processed_tickers)}\n")
    except Exception as e:
        print(f"⚠️  Could not read checkpoint: {e}. Starting fresh.\n")
else:
    print("🆕 No existing database. Starting fresh.\n")

# CSV column schema — must stay consistent across appends
FINAL_COLUMNS = (
    ['Ticker']
    + SENTIMENT_FEATURES
    + COUNT_FEATURES
    + ['Target']
)

now_dt  = datetime.datetime.now()
past_dt = now_dt - datetime.timedelta(days=30)

# ── Main Loop ─────────────────────────────────────────────
for ticker, cfg in NIFTY_50_CONFIG.items():
    if ticker in processed_tickers:
        print(f"⏭️  {ticker}: already in database.")
        continue

    print(f"\n{'═'*60}")
    print(f"  {ticker}  —  {cfg['full']}")
    print(f"{'═'*60}")

    all_news_rows = []   # Each entry: date, sentiment_val, sentiment_conf, category

    # ── English News ──────────────────────────────────────
    en_items = fetch_news_robust(cfg['full'], past_dt.date(), now_dt.date(), language='en')
    print(f"  EN: {len(en_items)} articles")

    for item in en_items:
        title = item.get('title', '').strip()
        url   = item.get('url', '')
        if not title:
            continue
        if any(ex.lower() in title.lower() for ex in cfg.get('exclude', [])):
            continue

        # Enrich with article body (headline + first 500 chars of body)
        body = fetch_article_body(url)
        analysis_text = (title + ". " + body[:500]) if body else title
        analysis_text = analysis_text[:512]

        try:
            pub = pd.to_datetime(item['published date']).tz_localize(None).normalize()
            sv, sc = get_clean_sentiment(analysis_text)
            cat     = categorize_news(title)  # Categorize from headline (cleaner signal)
            all_news_rows.append({
                'date': pub, 'sentiment_val': sv,
                'sentiment_conf': sc, 'category': cat,
                'display_text': title, 'translated': False, 'lang': 'en'
            })
        except Exception:
            continue

    # ── Hindi News ────────────────────────────────────────
    hi_items = fetch_news_robust(cfg['full'], past_dt.date(), now_dt.date(), language='hi')
    print(f"  HI: {len(hi_items)} articles")

    for item in hi_items:
        title_hi = item.get('title', '').strip()
        if not title_hi:
            continue

        title_en, was_translated = translate_to_english(title_hi, 'hi')
        if any(ex.lower() in title_en.lower() for ex in cfg.get('exclude', [])):
            continue

        try:
            pub = pd.to_datetime(item['published date']).tz_localize(None).normalize()
            sv, sc = get_clean_sentiment(title_en)
            cat     = categorize_news(title_en)
            display = title_en + (" [Translated from Hindi]" if was_translated else "")
            all_news_rows.append({
                'date': pub, 'sentiment_val': sv,
                'sentiment_conf': sc, 'category': cat,
                'display_text': display, 'translated': was_translated, 'lang': 'hi'
            })
        except Exception:
            continue

    if not all_news_rows:
        print(f"  ❌ No valid news found for {ticker}. Skipping.")
        continue

    df_raw_t = pd.DataFrame(all_news_rows)
    df_raw_t['date'] = pd.to_datetime(df_raw_t['date'])

    # ── Stock Data ────────────────────────────────────────
    try:
        df_stk = make_stock_target(
            ticker,
            past_dt.strftime('%Y-%m-%d'),
            now_dt.strftime('%Y-%m-%d')
        )
    except Exception as e:
        print(f"  ❌ Stock data error: {e}. Skipping.")
        continue

    if df_stk.empty:
        print(f"  ❌ Empty stock data. Skipping.")
        continue

    # ── Feature Engineering ───────────────────────────────
    df_feat_t   = build_daily_features(df_raw_t, df_stk.index)
    df_merged_t = df_stk.merge(df_feat_t, left_index=True, right_index=True, how='left').fillna(0)
    df_merged_t['Ticker'] = ticker

    for col in FINAL_COLUMNS:
        if col not in df_merged_t.columns:
            df_merged_t[col] = 0

    # ── Checkpoint Append ─────────────────────────────────
    write_header = not os.path.exists(CSV_FILENAME)
    df_merged_t[FINAL_COLUMNS].to_csv(
        CSV_FILENAME, mode='a', header=write_header, index=True
    )
    processed_tickers.add(ticker)
    n_translated = df_raw_t['translated'].sum()
    print(f"  ✅ Saved: {len(df_merged_t)} trading days | "
          f"{len(df_raw_t)} headlines ({n_translated} translated from Hindi)")

print(f"\n🎉 Batch complete! {len(processed_tickers)}/50 tickers in database.")
print(f"   File: {CSV_FILENAME} ({os.path.getsize(CSV_FILENAME)/1024:.1f} KB)")

# ============================================================
# CELL 9.5: Master Model Training — Walk-Forward + Stacking
#   Trains all 4 base models and the stacking meta-model
#   on the full master CSV produced by Cell 9.
# ============================================================
from IPython.display import display, clear_output, HTML
if not os.path.exists(CSV_FILENAME):
    print("⚠️  Run Cell 9 first to generate the master CSV.")
else:
    print(f"Loading {CSV_FILENAME}...")
    df_master = pd.read_csv(CSV_FILENAME, index_col=0)

    for col in ALL_FEATURES:
        if col not in df_master.columns:
            df_master[col] = 0.0
        df_master[col] = pd.to_numeric(df_master[col], errors='coerce').fillna(0)

    df_master['Target'] = pd.to_numeric(df_master['Target'], errors='coerce')
    df_master = df_master.dropna(subset=['Target'])
    df_master['Target'] = df_master['Target'].astype(int)

    X_master = df_master[ALL_FEATURES].astype('float32')
    y_master  = df_master['Target']

    print(f"Master dataset: {len(X_master)} samples | "
          f"{df_master['Ticker'].nunique()} tickers | "
          f"Class balance: {dict(y_master.value_counts())}")

    # ── Walk-Forward OOF for Stacking ─────────────────────
    MASTER_BASE_MODELS = {
        "LogReg":       LogisticRegression(random_state=42, max_iter=500),
        "RandomForest": RandomForestClassifier(n_estimators=200, random_state=42, n_jobs=-1),
        "XGBoost":      XGBClassifier(eval_metric='logloss', random_state=42,
                                      verbosity=0, n_estimators=200),
        "LightGBM":     lgb.LGBMClassifier(random_state=42, verbose=-1,
                                            n_estimators=200),
    }

    print("\nGenerating OOF predictions for stacking (walk-forward)...")
    fold_df_master, oof_master = walk_forward_oof(MASTER_BASE_MODELS, X_master, y_master, n_splits=5)
    print("\nPer-Fold Walk-Forward Accuracy:")
    display(fold_df_master)

    # ── Train Stacking Meta-Model ──────────────────────────
    print("\nTraining stacking meta-model...")
    master_stacker = build_stacking_meta(oof_master, y_master)

    # ── Retrain Base Models on Full Data ──────────────────
    print("\nRetraining base models on full master dataset...")
    master_lr  = LogisticRegression(random_state=42, max_iter=500)
    master_rf  = RandomForestClassifier(n_estimators=200, random_state=42, n_jobs=-1)
    master_xgb = XGBClassifier(eval_metric='logloss', random_state=42, verbosity=0, n_estimators=200)
    master_lgb = lgb.LGBMClassifier(random_state=42, verbose=-1, n_estimators=200)

    for name, mdl in [("LogReg", master_lr), ("RandomForest", master_rf),
                       ("XGBoost", master_xgb), ("LightGBM", master_lgb)]:
        mdl.fit(X_master, y_master)
        print(f"  ✅ {name} trained.")

    print(f"\n✅ All master models ready. Run Cell 9.7 → 9.8 → 9.9 → 10.")

# ============================================================
# CELL 9.7: Deep VRAM Scrubber
#   Clears ALL GPU-resident objects before reloading for UI.
#   Run this between Cell 9.5 and Cell 9.8.
# ============================================================

print(f"VRAM before scrub: {torch.cuda.memory_allocated()/1024**3:.3f} GB")

_pipeline_vars = [
    'bart_pipe', 'mistral_pipe', 'finbert_pipe', 'distilrob_pipe',
    'active_sentiment_pipe', '_z_model', '_z_tok',
    'model', 'tokenizer', 'pipeline'   # catch any stray names
]
for _v in _pipeline_vars:
    if _v in globals():
        del globals()[_v]

# Clear Colab output cache
for _c in ['_', '_1', '_2', '_3']:
    if _c in globals(): del globals()[_c]
if 'In'  in globals(): globals()['In'].clear()
if 'Out' in globals(): globals()['Out'].clear()

for _ in range(3):
    gc.collect()
torch.cuda.empty_cache()

print(f"VRAM after scrub : {torch.cuda.memory_allocated()/1024**3:.3f} GB")
print("\n✅ VRAM cleared. Proceed to Cell 9.8 to reload pipelines.")

# ============================================================
# CELL 9.8 (MODIFIED): Reload NLP Pipelines — BART Only
#   Removed: Zephyr-7B / Mistral entirely
#   VRAM budget: DistilRoBERTa 0.32 GB + BART 1.6 GB ≈ 1.9 GB total
#   Inference per query: ~5-8 seconds (was ~65 seconds with Zephyr)
# ============================================================
from transformers import pipeline, AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
import torch, gc

print("=" * 55)
print("RELOADING NLP PIPELINES FOR UI (BART-ONLY MODE)")
print("=" * 55)

# Safety clear before loading
for _v in list(globals().keys()):
    if any(x in str(type(globals()[_v])) for x in ['Pipeline', 'Model', 'Tokenizer']):
        del globals()[_v]
gc.collect()
torch.cuda.empty_cache()
print(f"VRAM before load: {torch.cuda.memory_allocated()/1024**3:.2f} GB")

# ── 1. Sentiment model ─────────────────────────────────────
if SENTIMENT_MODEL_NAME is None:
    print("⚠️  SENTIMENT_MODEL_NAME not set — defaulting to ProsusAI/finbert")
    SENTIMENT_MODEL_NAME = "ProsusAI/finbert"

print(f"\n[1/2] Loading sentiment model: {SENTIMENT_MODEL_NAME}")
active_sentiment_pipe = pipeline(
    "sentiment-analysis",
    model=SENTIMENT_MODEL_NAME,
    device=0 if device == "cuda" else -1
)
print(f"      VRAM: {torch.cuda.memory_allocated()/1024**3:.2f} GB")

# ── 2. BART (categorization) ──────────────────────────────
print("\n[2/2] Loading BART-Large (categorization)...")
bart_pipe = pipeline(
    "zero-shot-classification",
    model="facebook/bart-large-mnli",
    device=0 if device == "cuda" else -1
)

def bart_categorize(text: str) -> str:
    return bart_pipe(text[:512], VALID_CATEGORIES, multi_label=False)['labels'][0]

categorize_news = bart_categorize
print(f"      VRAM: {torch.cuda.memory_allocated()/1024**3:.2f} GB")

print(f"\n✅ Pipelines ready (BART-only mode):")
print(f"   Sentiment : {SENTIMENT_MODEL_NAME}")
print(f"   Category  : facebook/bart-large-mnli")
print(f"   Total VRAM: {torch.cuda.memory_allocated()/1024**3:.2f} GB")

# ============================================================
# CELL 9.9: Save All Models to Disk + Google Drive
#   Saves everything needed to run the ensemble in a separate project:
#     master_lr.pkl, master_rf.pkl, master_xgb.pkl, master_lgb.pkl
#     master_stacker.pkl  (None if insufficient training data)
#     sentiment model via save_pretrained()
#     config.json         (features, thresholds, model names)
#   Also copies to Google Drive if mounted.
# ============================================================

os.makedirs(SAVE_DIR, exist_ok=True)

# ── Verify master models exist ─────────────────────────────
_required = ['master_lr', 'master_rf', 'master_xgb', 'master_lgb']
_missing  = [v for v in _required if v not in globals()]
if _missing:
    print(f"⚠️  Missing models: {_missing}. Run Cell 9.5 first.")
else:
    # ── 1. Save sklearn / XGB / LGB models ────────────────
    print("Saving prediction models...")
    joblib.dump(master_lr,  f"{SAVE_DIR}/master_lr.pkl");  print("  ✅ master_lr.pkl")
    joblib.dump(master_rf,  f"{SAVE_DIR}/master_rf.pkl");  print("  ✅ master_rf.pkl")
    joblib.dump(master_xgb, f"{SAVE_DIR}/master_xgb.pkl"); print("  ✅ master_xgb.pkl")
    joblib.dump(master_lgb, f"{SAVE_DIR}/master_lgb.pkl"); print("  ✅ master_lgb.pkl")

    if 'master_stacker' in globals() and master_stacker is not None:
        joblib.dump(master_stacker, f"{SAVE_DIR}/master_stacker.pkl")
        print("  ✅ master_stacker.pkl")
    else:
        print("  ⚠️  master_stacker not available (will use average ensemble in UI).")

    # ── 2. Save sentiment model ────────────────────────────
    print(f"\nSaving sentiment model ({SENTIMENT_MODEL_NAME})...")
    if 'active_sentiment_pipe' in globals() and active_sentiment_pipe is not None:
        _sent_save_path = f"{SAVE_DIR}/sentiment_model"
        active_sentiment_pipe.model.save_pretrained(_sent_save_path)
        active_sentiment_pipe.tokenizer.save_pretrained(_sent_save_path)
        print(f"  ✅ Saved to {_sent_save_path}")
    else:
        print("  ⚠️  Sentiment pipeline not in memory. It will be downloaded from HuggingFace in other projects.")

    # ── 3. Save config ────────────────────────────────────
    config_data = {
        "sentiment_model_name":    SENTIMENT_MODEL_NAME,
        "categorization_model":    "facebook/bart-large-mnli",
        "mistral_model":           "HuggingFaceH4/zephyr-7b-beta",
        "valid_categories":        VALID_CATEGORIES,
        "sentiment_features":      SENTIMENT_FEATURES,
        "count_features":          COUNT_FEATURES,
        "all_features":            ALL_FEATURES,
        "return_threshold":        RETURN_THRESHOLD,
        "decay_lambda":            DECAY_LAMBDA,
        "news_lookback_days":      NEWS_LOOKBACK_DAYS,
        "bullish_keywords":        BULLISH_KEYWORDS,
        "bearish_keywords":        BEARISH_KEYWORDS,
        "saved_models": {
            "lr":       "master_lr.pkl",
            "rf":       "master_rf.pkl",
            "xgb":      "master_xgb.pkl",
            "lgb":      "master_lgb.pkl",
            "stacker":  "master_stacker.pkl",
            "sentiment_dir": "sentiment_model",
        },
        "loading_instructions": (
            "1. Load sklearn models with joblib.load(). "
            "2. Load sentiment model with pipeline('sentiment-analysis', model='./sentiment_model'). "
            "3. Load BART with pipeline('zero-shot-classification', model='facebook/bart-large-mnli'). "
            "4. Build feature vector using build_daily_features() logic. "
            "5. Predict: pass features through all 4 base models → stack probabilities → meta-model."
        )
    }
    with open(f"{SAVE_DIR}/config.json", 'w') as f:
        json.dump(config_data, f, indent=2)
    print("  ✅ config.json")

    # ── 4. Copy to Google Drive ────────────────────────────
    print("\nAttempting to save to Google Drive...")
    try:
        from google.colab import drive
        drive.mount('/content/drive', force_remount=False)
        import shutil
        drive_dest = '/content/drive/MyDrive/NiftySentimentModels'
        shutil.copytree(SAVE_DIR, drive_dest, dirs_exist_ok=True)
        print(f"  ✅ Copied to Google Drive: {drive_dest}")
    except Exception as e:
        print(f"  ℹ️  Google Drive not available ({str(e)[:60]}). Models saved locally only.")

    # ── Summary ───────────────────────────────────────────
    print(f"\n{'='*55}")
    print("SAVED MODEL SUMMARY")
    print(f"{'='*55}")
    for fn in os.listdir(SAVE_DIR):
        sz = os.path.getsize(os.path.join(SAVE_DIR, fn))
        if os.path.isfile(os.path.join(SAVE_DIR, fn)):
            print(f"  {fn:<35} {sz/1024:.1f} KB")
        else:
            dir_sz = sum(
                os.path.getsize(os.path.join(SAVE_DIR, fn, ff))
                for ff in os.listdir(os.path.join(SAVE_DIR, fn))
            )
            print(f"  {fn+'/':<35} {dir_sz/1024/1024:.1f} MB")

    print(f"\n✅ All models saved to {SAVE_DIR}")
    print("   To use in another project:")
    print("   1. Copy the entire saved_models/ folder")
    print("   2. Read config.json for feature names and thresholds")
    print("   3. Load .pkl files with joblib.load()")
    print("   4. Load sentiment model with HuggingFace pipeline from ./sentiment_model/")

# ============================================================
# CELL 10 (MODIFIED): Ensemble Dashboard — BART Only
#   Removed: Zephyr/Mistral loading, dual-bar chart, mistral_cats
#   Added:   Category confidence bar chart instead of BART vs Mistral
#   Inference time: ~5-8s per query (was ~65s)
# ============================================================
import warnings, datetime, urllib.parse, time
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import ipywidgets as widgets
import joblib, os
from IPython.display import display, clear_output, HTML

warnings.filterwarnings('ignore')

# ── Load prediction models from disk (timed) ──────────────
print("⏱️  Loading prediction models from disk...")
_t_load = time.time()

try:
    ui_lr      = joblib.load(f"{SAVE_DIR}/master_lr.pkl")
    ui_rf      = joblib.load(f"{SAVE_DIR}/master_rf.pkl")
    ui_xgb     = joblib.load(f"{SAVE_DIR}/master_xgb.pkl")
    ui_lgb     = joblib.load(f"{SAVE_DIR}/master_lgb.pkl")
    _has_stk   = os.path.exists(f"{SAVE_DIR}/master_stacker.pkl")
    ui_stacker = joblib.load(f"{SAVE_DIR}/master_stacker.pkl") if _has_stk else None
    print(f"   ✅ All models loaded in {time.time()-_t_load:.3f}s")
    print(f"   Stacker: {'available' if ui_stacker else 'not available (using weighted average)'}")
except FileNotFoundError:
    print("⚠️  Saved models not found. Using in-memory models.")
    ui_lr      = master_lr      if 'master_lr'      in globals() else None
    ui_rf      = master_rf      if 'master_rf'      in globals() else None
    ui_xgb     = master_xgb     if 'master_xgb'     in globals() else None
    ui_lgb     = master_lgb     if 'master_lgb'     in globals() else None
    ui_stacker = master_stacker if 'master_stacker' in globals() else None


def create_feature_row(category: str, sentiment_val: float) -> pd.DataFrame:
    """Build 12-column feature vector — columns in exact training order."""
    row = {}
    for cat in VALID_CATEGORIES:
        row[f"Sentiment_{cat}"] = sentiment_val if cat == category else 0.0
    for cat in VALID_CATEGORIES:
        row[f"Count_{cat}"] = 1 if cat == category else 0
    return pd.DataFrame([row])[ALL_FEATURES].astype('float32')


def ensemble_predict(feature_row: pd.DataFrame):
    """
    Run all 4 base models, combine with stacker (or weighted average).
    Returns (probs dict, consensus float).
    """
    probs = {
        'LogReg':       ui_lr.predict_proba(feature_row)[0][1]  if ui_lr  else 0.5,
        'RandomForest': ui_rf.predict_proba(feature_row)[0][1]  if ui_rf  else 0.5,
        'XGBoost':      ui_xgb.predict_proba(feature_row)[0][1] if ui_xgb else 0.5,
        'LightGBM':     ui_lgb.predict_proba(feature_row)[0][1] if ui_lgb else 0.5,
    }
    if ui_stacker is not None:
        oof_input = np.array([[v for v in probs.values()]])
        consensus = ui_stacker.predict_proba(oof_input)[0][1]
    else:
        weights   = [abs(p - 0.5) * 2 + 0.1 for p in probs.values()]
        consensus = sum(p * w for p, w in zip(probs.values(), weights)) / sum(weights)
    return probs, consensus


# ── UI ────────────────────────────────────────────────────
print("\n" + "=" * 55)
print("🤖  SENTIMENT ENSEMBLE DASHBOARD (BART-ONLY)  🤖")
print(f"    Models loaded from disk in {time.time()-_t_load:.3f}s")
print("=" * 55)

stock_dd  = widgets.Dropdown(
    options=list(NIFTY_50_CONFIG.keys()), value="RELIANCE.NS", description='Stock:'
)
date_pick = widgets.DatePicker(description='Date:', value=datetime.date.today())
run_btn   = widgets.Button(
    description='▶ Run Analysis', button_style='success',
    layout=widgets.Layout(width='200px')
)
out_area  = widgets.Output()
display(widgets.VBox([widgets.HBox([stock_dd, date_pick]), run_btn, out_area]))


def on_run(b):
    with out_area:
        clear_output(wait=True)

        ticker  = stock_dd.value
        tdate   = date_pick.value
        cfg     = NIFTY_50_CONFIG[ticker]
        start_d = tdate - datetime.timedelta(days=3)
        end_d   = tdate + datetime.timedelta(days=1)

        print(f"{'='*55}")
        print(f"Analyzing {ticker} ({cfg['full']}) — {tdate}")
        print(f"{'='*55}")

        # ── Fetch EN + HI news ────────────────────────────
        print("Fetching news...")
        t_fetch  = time.time()
        en_items = fetch_news_robust(cfg['full'], start_d, end_d, 'en')
        hi_items = fetch_news_robust(cfg['full'], start_d, end_d, 'hi')
        print(f"  EN: {len(en_items)} | HI: {len(hi_items)} | "
              f"Fetched in {time.time()-t_fetch:.1f}s")

        if not en_items and not hi_items:
            print("❌ No news found for this date/ticker.")
            return

        # ── Process headlines ─────────────────────────────
        display_rows = []

        for item in en_items:
            title = item.get('title', '').strip()
            if not title: continue
            if any(ex.lower() in title.lower() for ex in cfg.get('exclude', [])): continue
            body  = fetch_article_body(item.get('url', ''))
            atxt  = (title + ". " + body[:400]) if body else title
            sv, sc = get_clean_sentiment(atxt[:512])
            cat    = bart_categorize(title)
            display_rows.append({
                'display': title, 'sv': sv, 'sc': sc,
                'category': cat, 'lang': 'EN', 'translated': False
            })

        for item in hi_items:
            title_hi = item.get('title', '').strip()
            if not title_hi: continue
            title_en, was_tr = translate_to_english(title_hi, 'hi')
            if any(ex.lower() in title_en.lower() for ex in cfg.get('exclude', [])): continue
            sv, sc = get_clean_sentiment(title_en[:512])
            cat    = bart_categorize(title_en)
            tag    = " [Translated from Hindi]" if was_tr else ""
            display_rows.append({
                'display': title_en + tag, 'sv': sv, 'sc': sc,
                'category': cat, 'lang': 'HI', 'translated': was_tr
            })

        if not display_rows:
            print("❌ All headlines filtered by exclusion rules.")
            return

        print(f"🚀 NLP inference on {len(display_rows)} headlines...")
        t_inf = time.time()

        # ── Aggregate ─────────────────────────────────────
        svs   = np.array([r['sv'] for r in display_rows], dtype=float)
        scs   = np.array([r['sc'] for r in display_rows], dtype=float)
        total_wt    = scs.sum()
        w_sentiment = (svs * scs).sum() / total_wt if total_wt > 0 else 0.0

        cats        = [r['category'] for r in display_rows]
        top_cat     = pd.Series(cats).mode()[0]
        cat_counts  = pd.Series(cats).value_counts()

        print(f"⏱️  Done in {time.time()-t_inf:.1f}s | "
              f"Top category: {top_cat} | w_sentiment: {w_sentiment:+.3f}")

        # ── Predict ───────────────────────────────────────
        feature_row        = create_feature_row(top_cat, w_sentiment)
        probs, consensus   = ensemble_predict(feature_row)
        signal_label       = "BULLISH 🟢" if consensus > 0.5 else "BEARISH 🔴"

        # ── Plot ──────────────────────────────────────────
        fig, axes = plt.subplots(1, 3, figsize=(16, 5))

        # Panel 1: Model predictions
        model_names = list(probs.keys())
        model_probs = [p * 100 for p in probs.values()]
        colors      = ['#2ecc71' if p > 50 else '#e74c3c' for p in model_probs]
        bars = axes[0].bar(model_names, model_probs, color=colors, edgecolor='white', linewidth=0.5)
        axes[0].axhline(50, color='black', linestyle='--', linewidth=1, label='Baseline (50%)')
        axes[0].axhline(consensus * 100, color='gold', linestyle='-',
                        linewidth=2, label=f'Stacked Consensus ({consensus*100:.1f}%)')
        for bar, prob in zip(bars, model_probs):
            axes[0].text(bar.get_x() + bar.get_width()/2,
                         bar.get_height() + 1, f'{prob:.1f}%',
                         ha='center', va='bottom', fontsize=9, fontweight='bold')
        axes[0].set_title(f'Model Predictions — {ticker}')
        axes[0].set_ylabel('Bullish Probability (%)')
        axes[0].set_ylim(0, 110)
        axes[0].legend(fontsize=8)

        # Panel 2: Category distribution
        cat_series = cat_counts.reindex(VALID_CATEGORIES, fill_value=0)
        cat_colors = ['#f39c12' if c == top_cat else '#3498db' for c in cat_series.index]
        axes[1].barh(cat_series.index, cat_series.values,
                     color=cat_colors, edgecolor='white')
        axes[1].set_title(f'Category Distribution\n(orange = dominant: {top_cat})')
        axes[1].set_xlabel('Headline Count')

        # Panel 3: Sentiment breakdown
        sent_counts = [int((svs == v).sum()) for v in [-1, 0, 1]]
        axes[2].bar(['Bearish (-1)', 'Neutral (0)', 'Bullish (+1)'],
                    sent_counts,
                    color=['#e74c3c', '#95a5a6', '#2ecc71'],
                    edgecolor='white')
        axes[2].set_title(f'Sentiment Distribution\n'
                          f'(weighted avg: {w_sentiment:+.3f})')
        axes[2].set_ylabel('Count')

        plt.suptitle(
            f"{cfg['full']} ({ticker})  |  {tdate}  |  "
            f"Consensus: {signal_label} ({consensus*100:.1f}%)",
            fontsize=12, fontweight='bold', y=1.02
        )
        plt.tight_layout()
        plt.show()

        # ── Summary ───────────────────────────────────────
        print("\n" + "=" * 55)
        print(f"  STACKED CONSENSUS  : {signal_label} ({consensus*100:.1f}%)")
        print(f"  Dominant category  : {top_cat}")
        print(f"  Weighted sentiment : {w_sentiment:+.4f}")
        print(f"  Headlines analysed : {len(display_rows)} "
              f"({sum(r['translated'] for r in display_rows)} translated from Hindi)")
        print("  Model breakdown:")
        for name, prob in probs.items():
            bar = "█" * int(prob * 20)
            print(f"    {name:<16}: {prob*100:.1f}% {bar}")
        print("=" * 55)

        # ── Headline Table ────────────────────────────────
        df_table = pd.DataFrame({
            'Headline'  : [r['display'] for r in display_rows],
            'Lang'      : [r['lang']    for r in display_rows],
            'Sentiment' : [f"{r['sv']:+d} (conf: {r['sc']:.2f})" for r in display_rows],
            'Category'  : [r['category'] for r in display_rows],
        })
        display(HTML(
            df_table.to_html(index=False, classes='table table-striped',
                             border=0, justify='left')
        ))


run_btn.on_click(on_run)