#!/usr/bin/env python
"""Count the work the validity screen would have pre-empted.

Both the DSM and the IJCISIM versions of this study make a quantitative claim
about *effort*: the screen is two regressions on artefacts already in hand,
whereas the downstream programme it should have pre-empted is several hundred
model fits.  That claim must be counted from the result files rather than
asserted, so this script derives every number in the cost table directly from
``results/`` and emits

    tables/tab_cost.tex     the table fragment the manuscript inputs
    macros_cost.tex         the \\newcommand definitions the prose quotes

Nothing here re-runs an analysis; it only counts what the earlier steps left
behind.  Run it after 03/04/08/09 have written their outputs.
"""
from __future__ import annotations

import argparse
import csv
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)


def _rows(path: str) -> list[dict]:
    with open(path, newline="", encoding="utf-8") as fh:
        return list(csv.DictReader(fh))


def _fmt(n: int) -> str:
    """Thousands separator in the form LaTeX renders without a math shift."""
    return f"{n:,}"


def collect(results: str) -> dict:
    """Count each stage of the study from the artefacts it produced."""
    surfaces = [f for f in sorted(os.listdir(results))
                if f.startswith("exponent_surface_") and f.endswith(".csv")]
    grid_per_horizon = len(_rows(os.path.join(results, surfaces[0])))
    grid_total = sum(len(_rows(os.path.join(results, f))) for f in surfaces)

    univariate = _rows(os.path.join(results, "univariate.csv"))
    horserace = _rows(os.path.join(results, "horse_race.csv"))
    robust = _rows(os.path.join(results, "robustness.csv"))
    gate = _rows(os.path.join(results, "gate_by_year_newsrows.csv"))

    years = sorted({r["test_year"] for r in gate})
    variants = sorted({r["variant"] for r in gate})
    horizons = sorted({int(r["horizon"]) for r in gate})

    with open(os.path.join(results, "panel_meta.json"), encoding="utf-8") as fh:
        meta = json.load(fh)
    with open(os.path.join(results, "convergent_validity.json"), encoding="utf-8") as fh:
        cv = json.load(fh)

    # The screen itself: one regression per criterion, plus the decile profile
    # that has to be inspected before either is summarised.  No model calls:
    # staleness comes from the corpus, outcome magnitude from prices already
    # required by the study.
    screen_regressions = 2
    screen_profiles = 1
    screen_model_calls = 0

    return {
        "GridPerHorizon": grid_per_horizon,
        "GridTotal": grid_total,
        "GridHorizons": len(surfaces),
        "UnivariateFits": len(univariate),
        "HorseRaceCoefs": len(horserace),
        "RobustnessFits": len(robust),
        "GateFits": len(gate),
        "GateYears": len(years),
        "GateVariants": len(variants),
        "GateHorizons": len(horizons),
        "GateYearFirst": years[0],
        "GateYearLast": years[-1],
        "DownstreamTotal": (grid_total + len(univariate) + len(horserace)
                            + len(robust) + len(gate)),
        "ScreenRegressions": screen_regressions,
        "ScreenProfiles": screen_profiles,
        "ScreenModelCalls": screen_model_calls,
        "ScreenTotal": screen_regressions + screen_profiles,
        "ScoredForScreen": cv["n_with_prior"],
        "HeadlinesScored": meta["headlines_scored"],
        "PriorDocMedian": int(cv["median_prior_docs"]),
    }


TABLE = r"""% Auto-generated by analysis/10_cost_accounting.py -- do not edit by hand.
\begin{table}[htbp]
\centering
\caption{What the screen costs and what it pre-empts. The upper panel is the
validity screen of Section~\ref{sec:screen}; the lower panel is the modelling
programme reported in Section~\ref{sec:results}, whose every conclusion the
screen anticipates. Counts are of fitted objects, derived from the stored result
files rather than asserted. Neither criterion in the upper panel required a
labelled example or an additional call to the scoring model.}
\label{tab:cost}
\begin{tabular}{@{}llr@{}}
\toprule
Stage & Unit counted & Count \\
\midrule
\multicolumn{3}{@{}l}{\textit{Panel A: the validity screen}} \\
Criterion regressions & one per attribute & SCREEN_REGRESSIONS \\
Decile profiles inspected & one per criterion pair & SCREEN_PROFILES \\
Additional scoring-model calls & headlines rescored & SCREEN_MODEL_CALLS \\
\textbf{Total fitted objects} & & \textbf{SCREEN_TOTAL} \\
\addlinespace
\multicolumn{3}{@{}l}{\textit{Panel B: the downstream programme}} \\
Predictive regressions & aggregator $\times$ horizon & UNIVARIATE_FITS \\
Nested horse-race coefficients & term $\times$ horizon & HORSERACE_COEFS \\
Exponent-grid evaluations & GRID_PER_HORIZON per horizon, GRID_HORIZONS horizons & GRID_TOTAL \\
Robustness re-estimations & variation $\times$ setting $\times$ horizon & ROBUSTNESS_FITS \\
Walk-forward selective forecasters & GATE_VARIANTS variants $\times$ GATE_YEARS years $\times$ GATE_HORIZONS horizons & GATE_FITS \\
\textbf{Total fitted objects} & & \textbf{DOWNSTREAM_TOTAL} \\
\botrule
\end{tabular}
\end{table}
"""


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", default=os.path.join(ROOT, "results"))
    ap.add_argument("--tables", default=os.path.join(ROOT, "tables"))
    ap.add_argument("--macros", default=os.path.join(ROOT, "macros_cost.tex"))
    ap.add_argument("--no-latex", action="store_true",
                    help="emit only results/cost_accounting.json, for a Word build")
    args = ap.parse_args()

    c = collect(args.results)

    # The counts themselves, for whichever manuscript build consumes them.
    with open(os.path.join(args.results, "cost_accounting.json"), "w",
              encoding="utf-8") as fh:
        json.dump(c, fh, indent=1)
    if args.no_latex:
        print(json.dumps(c, indent=1))
        print("wrote", os.path.join(args.results, "cost_accounting.json"))
        return

    os.makedirs(args.tables, exist_ok=True)
    body = TABLE
    for key, placeholder in [
        ("ScreenRegressions", "SCREEN_REGRESSIONS"),
        ("ScreenProfiles", "SCREEN_PROFILES"),
        ("ScreenModelCalls", "SCREEN_MODEL_CALLS"),
        ("ScreenTotal", "SCREEN_TOTAL"),
        ("UnivariateFits", "UNIVARIATE_FITS"),
        ("HorseRaceCoefs", "HORSERACE_COEFS"),
        ("GridPerHorizon", "GRID_PER_HORIZON"),
        ("GridHorizons", "GRID_HORIZONS"),
        ("GridTotal", "GRID_TOTAL"),
        ("RobustnessFits", "ROBUSTNESS_FITS"),
        ("GateVariants", "GATE_VARIANTS"),
        ("GateYears", "GATE_YEARS"),
        ("GateHorizons", "GATE_HORIZONS"),
        ("GateFits", "GATE_FITS"),
        ("DownstreamTotal", "DOWNSTREAM_TOTAL"),
    ]:
        body = body.replace(placeholder, _fmt(c[key]))

    with open(os.path.join(args.tables, "tab_cost.tex"), "w", encoding="utf-8") as fh:
        fh.write(body)

    # LaTeX control sequences may contain letters only, so horizons and other
    # numeric suffixes are spelled out wherever they appear in a macro name.
    lines = ["% Auto-generated by analysis/10_cost_accounting.py -- do not edit by hand."]
    for key in ("GridPerHorizon", "GridTotal", "GridHorizons", "UnivariateFits",
                "HorseRaceCoefs", "RobustnessFits", "GateFits", "GateYears",
                "GateVariants", "GateHorizons", "GateYearFirst", "GateYearLast",
                "DownstreamTotal", "ScreenRegressions", "ScreenProfiles",
                "ScreenModelCalls", "ScreenTotal", "ScoredForScreen",
                "HeadlinesScored", "PriorDocMedian"):
        val = c[key]
        lines.append("\\newcommand{\\%s}{%s}" % (
            key, _fmt(val) if isinstance(val, int) else val))
    with open(args.macros, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")

    print(json.dumps(c, indent=1))
    print("wrote", os.path.join(args.tables, "tab_cost.tex"))
    print("wrote", args.macros)


if __name__ == "__main__":
    main()
